name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.2
    steps:
      - uses: actions/checkout@v2
      - name: Install plugins
        run: godot -s plug.gd install
      - name: Show plugins are installed
        run: |
          ls -l addons
          ls -l .plugged
      - name: Uninstall plugins
        run: godot -s plug.gd uninstall
      - name: Show plugins are uninstalled
        run: |
          ls -l addons
          ls -l .plugged
